<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

D:\Jupyter\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [5]:
df = pd.read_csv("fake_or_real_news.csv", encoding = 'unicode_escape')
df

,text,label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U.S. Secretary of State John F. Kerry said Mon...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"— Kaydee King (@KaydeeKing) November 9, 2016...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It's primary day in New York and front-runners...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,The State Department told the Republican Natio...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7791,The ‘P’ in PBS Should Stand for ‘Plutocr...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7793,"ADDIS ABABA, Ethiopia —President Obama conve...",REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [7]:
df.dropna(subset=['text'], inplace=True)
df.dropna(subset=['label'], inplace=True)
df

,text,label,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,U.S. Secretary of State John F. Kerry said Mon...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"— Kaydee King (@KaydeeKing) November 9, 2016...",FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,It's primary day in New York and front-runners...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7790,The State Department told the Republican Natio...,REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7791,The ‘P’ in PBS Should Stand for ‘Plutocr...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7793,"ADDIS ABABA, Ethiopia —President Obama conve...",REAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [8]:
#df2=df.drop(df.iloc[:,2:139], axis=1)
#df2

# Keep only required columns
df2 = df[['text', 'label']]

In [9]:
#Showing label information which are not FAKE or REAL
#df_filtered = df2[~df2['label'].isin(['FAKE', 'REAL'])]
#df_filtered

# Keep only valid labels
df2 = df2[df2['label'].isin(['FAKE', 'REAL'])]

In [10]:
# Deleting rows where label is not FAKE or REAL
#df2 = df2.loc[(df2["label"]=='FAKE') | (df2["label"]=='REAL')]
df2

,text,label
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,"— Kaydee King (@KaydeeKing) November 9, 2016...",FAKE
4,It's primary day in New York and front-runners...,REAL
...,...,...
7790,The State Department told the Republican Natio...,REAL
7791,The ‘P’ in PBS Should Stand for ‘Plutocr...,FAKE
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
7793,"ADDIS ABABA, Ethiopia —President Obama conve...",REAL


In [11]:
#df.label.value_counts()
df2.isnull().sum()

text     0
label    0
dtype: int64

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6315 entries, 0 to 7794
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    6315 non-null   object
 1   label   6315 non-null   object
dtypes: object(2)
memory usage: 148.0+ KB


In [16]:
df2.shape

(6315, 2)

In [17]:
df2

,text,label
0,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,"— Kaydee King (@KaydeeKing) November 9, 2016...",FAKE
4,It's primary day in New York and front-runners...,REAL
...,...,...
7790,The State Department told the Republican Natio...,REAL
7791,The ‘P’ in PBS Should Stand for ‘Plutocr...,FAKE
7792,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
7793,"ADDIS ABABA, Ethiopia —President Obama conve...",REAL


<h3>Train test split</h3>

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df2.text, df2.label, test_size=0.2, random_state=1)

In [19]:
X_train.shape

(5052,)

In [20]:
X_test.shape

(1263,)

In [21]:
X_test

1602    Posted on November 4, 2013 by joandarc | 12 Co...
7023    Today the White House will hold the annual Eas...
3126    \nA grim new Ministry of Defense ( MoD ) repor...
5723    The Bureau of Land Management (BLM) claims to ...
2341    The Kremlin on Friday played down the possibil...
                              ...                        
2423    19 mins ago 3 Views 0 Comments 0 Likes It's fa...
6212    Home | World | Brexit Lost: Scuppered By May a...
500     The federal government must make regular inter...
4852    Both Donald Trump and Hillary Clinton have str...
2642    (CNN) Sen. John McCain is chastising GOP leade...
Name: text, Length: 1263, dtype: object

In [22]:
X_train

2789    More than 50 individuals and entities have she...
4976    FBI Director may be sacked for intrusion into ...
1906    The White House made formal veto threats Wedne...
5312    Republican presidential candidate John Kasich ...
3076    The Supreme Court gutted a key portion of the ...
                              ...                        
1220    The battle over the budget that President Obam...
6557    Email \nWell, this isn’t good. \nMost people...
4979    Chris Christie depicts Marco Rubio as a truant...
235      Why Hillary Won't Unleash WWIII By Pepe Escob...
6522    On 23 September 1952, vice presidential candid...
Name: text, Length: 5052, dtype: object

In [199]:
type(y_train)

pandas.core.series.Series

In [17]:
X_train.values

array(['Running mates? Itâ\x80\x99s not even May, and already weâ\x80\x99re talking running mates? Then let me toss Elizabeth Warrenâ\x80\x99s name into the mix.\n\nIâ\x80\x99m making several assumptions here â\x80\x94 in a year when assuming anything is dangerous. First, I believe Ted Cruzâ\x80\x99s desperate gamble of adding Carly Fiorina to his â\x80\x9cticketâ\x80\x9d will fail. He was right to throw some kind of Hail Mary, but I donâ\x80\x99t see how Fiorina attracts enough new support for Cruz to win the Indiana primary on Tuesday. And if he loses there, heâ\x80\x99s pretty much toast.\n\nDonald Trumpâ\x80\x99s landslide wins this week in the Northeast gave him a bigger haul of convention delegates than even his most optimistic boosters had expected. If momentum still counts for anything in politics, Trump has it. And if he wins Indiana â\x80\x94 polls show him with about a six-point lead â\x80\x94 his path to the Republican nomination looks wide enough to taxi the rest of the wa

In [23]:
X_train.values.shape

(5052,)

In [25]:
type(X_train.values)

numpy.ndarray

<h3>Create bag of words representation using CountVectorizer</h3>

In [26]:
# from sklearn.feature_extraction.text import CountVectorizer

# v = CountVectorizer()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_df=0.7
)

X_train_tfidf = tfidf.fit_transform(X_train.values.astype('U'))

In [27]:
statements = [
            'Google has started providing unlimited cloud storage for its users',
            'Joe Biden is the US President'
         ]

statements_cv = tfidf.fit_transform(statements)
statements_cv

<2x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [28]:
statements_cv.toarray()

array([[0.        , 0.37796447, 0.37796447, 0.        , 0.        ,
        0.37796447, 0.37796447, 0.37796447, 0.37796447, 0.37796447],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [30]:
tfidf.get_feature_names_out()

array(['biden', 'cloud', 'google', 'joe', 'president', 'providing',
       'started', 'storage', 'unlimited', 'users'], dtype=object)

In [32]:
pd.DataFrame(statements_cv.toarray(), columns=tfidf.get_feature_names_out())

,biden,cloud,google,joe,president,providing,started,storage,unlimited,users
0,0.00000,0.377964,0.377964,0.00000,0.00000,0.377964,0.377964,0.377964,0.377964,0.377964
1,0.57735,0.000000,0.000000,0.57735,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000


In [38]:
tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train.values.astype('U'))
X_train_tfidf

<5052x67644 sparse matrix of type '<class 'numpy.float64'>'
	with 1724538 stored elements in Compressed Sparse Row format>

In [39]:
X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
X_train_tfidf.shape

(5052, 67644)

In [41]:
X_train_tfidf[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [42]:
tfidf.get_feature_names_out()

array(['00', '000', '0000', ..., 'ðºð', 'ð¾ðºñ', 'ø¹ø'], dtype=object)

In [43]:
pd.DataFrame(X_train_tfidf.toarray(), columns=tfidf.get_feature_names_out())

,00,000,0000,000000031,00000031,000035,00006,0001pt,0002,000ft,...,î²,îµî,îµî¼î²ï,î½î¹îºî,ð²ð½ð,ð³,ð¹,ðºð,ð¾ðºñ,ø¹ø
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5047,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [45]:
tfidf.vocabulary_

{'more': 40035,
 'than': 60270,
 '50': 1414,
 'individuals': 30876,
 'and': 4253,
 'entities': 21092,
 'have': 27974,
 'shelled': 54684,
 'out': 43522,
 'at': 5716,
 'least': 35249,
 '1â': 727,
 'million': 39115,
 'apiece': 4719,
 'to': 60982,
 'big': 7901,
 'money': 39848,
 'groups': 26939,
 'backing': 6388,
 'presidential': 47246,
 'candidates': 10463,
 'with': 66395,
 'close': 12607,
 'half': 27450,
 'of': 42753,
 'the': 60299,
 'donors': 18992,
 'giving': 25990,
 'super': 58624,
 'pac': 43994,
 'aligned': 3688,
 'former': 24377,
 'florida': 23965,
 'governor': 26466,
 'jeb': 32681,
 'bush': 9993,
 '15': 320,
 'months': 39957,
 'go': 26187,
 'before': 7327,
 'election': 20292,
 'day': 16146,
 'already': 3856,
 'contributed': 14237,
 '272': 989,
 '5â': 1575,
 'independent': 30791,
 'supporting': 58742,
 'large': 34891,
 'republican': 50802,
 'field': 23384,
 'four': 24484,
 'times': 60854,
 '67â': 1658,
 'raised': 48991,
 'through': 60651,
 'their': 60343,
 'official': 42805,
 'campa

<h3>Train the naive bayes model</h3>

In [46]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [47]:
X_test

1602    Posted on November 4, 2013 by joandarc | 12 Co...
7023    Today the White House will hold the annual Eas...
3126    \nA grim new Ministry of Defense ( MoD ) repor...
5723    The Bureau of Land Management (BLM) claims to ...
2341    The Kremlin on Friday played down the possibil...
                              ...                        
2423    19 mins ago 3 Views 0 Comments 0 Likes It's fa...
6212    Home | World | Brexit Lost: Scuppered By May a...
500     The federal government must make regular inter...
4852    Both Donald Trump and Hillary Clinton have str...
2642    (CNN) Sen. John McCain is chastising GOP leade...
Name: text, Length: 1263, dtype: object

<h3>Evaluate Performance</h3>

In [49]:
X_test_tfidf = tfidf.transform(X_test)

In [50]:
X_test_tfidf.toarray()

array([[0.        , 0.02282742, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [51]:
X_test_tfidf.toarray().shape

(1263, 67644)

In [52]:
model.score(X_test_tfidf, y_test)

0.7806809184481394

In [53]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_tfidf)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        FAKE       0.98      0.58      0.73       644
        REAL       0.69      0.99      0.82       619

    accuracy                           0.78      1263
   macro avg       0.84      0.78      0.77      1263
weighted avg       0.84      0.78      0.77      1263



In [54]:
statements = [
            'Google has started providing unlimited cloud storage for its users',
            'Joe Biden is the US president'
]

In [55]:
statements_count = tfidf.transform(statements)
statements_count.toarray().shape

(2, 67644)

In [56]:
statements_count.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
#statements_count.toarray().shape
model.predict(statements_count)

array(['FAKE', 'REAL'], dtype='<U4')